#-*- encoding: utf-8 -*-
import math
PREMISSA='''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

def main():
	first = 0
	Second = 1
	Number = first + Second
	soma = 0
	while Number < 4000000:
		Number = first + Second
		first = Second
		Second = Number
		if (Number % 2) == 0:
			soma += Number
	print(soma)



if __name__ == '__main__':
	main()